using System.Data;
using System.Text;

namespace DataAgent;

// Helper class generated by ChatGPT
public class CsvFormatter
{
    public static string DataTableToCsv(DataTable dataTable)
    {
        var csvData = new StringBuilder();

        // Add the headers
        for (int i = 0; i < dataTable.Columns.Count; i++)
        {
            csvData.Append(dataTable.Columns[i].ColumnName);
            if (i < dataTable.Columns.Count - 1)
                csvData.Append(',');
        }
        csvData.AppendLine();

        // Add the data rows
        foreach (DataRow row in dataTable.Rows)
        {
            for (int i = 0; i < dataTable.Columns.Count; i++)
            {
                string value = row[i].ToString();

                // Check if the value contains a comma and place it in quotes if it does
                if (value.Contains(","))
                    value = $"\"{value}\"";

                // Replace any newlines in the value with spaces to prevent breaking the CSV format
                value = value.Replace("\r", " ").Replace("\n", " ");

                csvData.Append(value);

                if (i < dataTable.Columns.Count - 1)
                    csvData.Append(",");
            }
            csvData.AppendLine();
        }

        return csvData.ToString();
    }
}
